name: Compatibility

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  e2e:
    uses: ./.github/workflows/_e2e-compatibility.yml
    with:
      run_canaries: true
